services:
  - type: web
    name: bookstore
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MongodbURI
        sync: false 